/**
 * wt init [options]
 *
 * Generates a .worktreerc file for the current repository by:
 * 1. Detecting project types (node, python, rust, go)
 * 2. Scanning for .env files
 * 3. Writing a tailored .worktreerc
 * 4. Prompting for confirmation (unless --defaults)
 */

import path from "node:path";
import fs from "node:fs/promises";
import { logger } from "../utils/logger.ts";
import type { ParsedFlags } from "../index.ts";
import { getRepoRoot } from "../core/git.ts";
import { detectProjectTypes } from "../core/detector.ts";
import type { DetectedEcosystem } from "../core/types.ts";

const HELP = `
wt init [options]

Interactively generate a .worktreerc configuration file for this repository.

OPTIONS:
    --defaults      Use sensible defaults without prompting

BEHAVIOR:
    1. Detect project types in the current directory
    2. Scan for .env files
    3. Generate a .worktreerc with detected settings
    4. Prompt to confirm before writing (unless --defaults)

EXAMPLES:
    wt init                   Interactive init
    wt init --defaults        Write defaults without prompts
`.trim();

// ---------------------------------------------------------------------------
// .env file discovery
// ---------------------------------------------------------------------------

async function findEnvFiles(dir: string): Promise<string[]> {
  const found: string[] = [];
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      if (
        entry.name === ".env" ||
        entry.name.startsWith(".env.") ||
        entry.name.endsWith(".env")
      ) {
        found.push(entry.name);
      }
    }

    // Scan one level deep for service directories
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      try {
        const subDir = path.join(dir, entry.name);
        const subEntries = await fs.readdir(subDir, { withFileTypes: true });
        for (const sub of subEntries) {
          if (sub.isFile() && (sub.name === ".env" || sub.name.startsWith(".env."))) {
            found.push(`${entry.name}/${sub.name}`);
          }
        }
      } catch {
        // ignore unreadable subdirs
      }
    }
  } catch {
    // ignore
  }
  return found;
}

// ---------------------------------------------------------------------------
// TOML generation
// ---------------------------------------------------------------------------

function buildWorktreerc(
  ecosystems: DetectedEcosystem[],
  envFiles: string[],
  repoName: string,
): string {
  const lines: string[] = [
    `# .worktreerc — worktree automation configuration`,
    `# Generated by wt init. Safe to commit (no secrets).`,
    ``,
    `version = 1`,
    ``,
  ];

  // [detect]
  if (ecosystems.length > 0) {
    const types = ecosystems.map((e) => `"${e.type}"`).join(", ");
    lines.push(`[detect]`);
    lines.push(`types = [${types}]`);
    lines.push(``);
  }

  // [deps]
  const hasNode = ecosystems.some((e) => e.type === "node");
  const hasPython = ecosystems.some((e) => e.type === "python");
  const nodePm = ecosystems.find((e) => e.type === "node")?.pm ?? "bun";
  const pythonPm = ecosystems.find((e) => e.type === "python")?.pm ?? "uv";

  if (hasNode || hasPython) {
    lines.push(`[deps]`);
    lines.push(`enabled = true`);
    if (hasNode) lines.push(`node_pm = "${nodePm}"`);
    if (hasPython) lines.push(`python_pm = "${pythonPm}"`);
    lines.push(``);
  }

  // [python]
  if (hasPython) {
    lines.push(`[python]`);
    lines.push(`version = "python3"`);
    lines.push(`editable = false`);
    lines.push(``);
  }

  // [env]
  if (envFiles.length > 0) {
    const safeEnvFiles = envFiles.filter(
      (f) => !f.includes("production") && !f.includes("staging"),
    );
    const excludeFiles = envFiles.filter(
      (f) => f.includes("production") || f.includes("staging"),
    );

    lines.push(`[env]`);
    lines.push(`strategy = "symlink"`);
    if (safeEnvFiles.length > 0) {
      lines.push(`patterns = [`);
      for (const f of safeEnvFiles) {
        lines.push(`    "${f}",`);
      }
      lines.push(`]`);
    }
    if (excludeFiles.length > 0) {
      lines.push(`exclude = [`);
      for (const f of excludeFiles) {
        lines.push(`    "${f}",`);
      }
      lines.push(`]`);
    }
    lines.push(``);
  } else {
    lines.push(`[env]`);
    lines.push(`strategy = "symlink"`);
    lines.push(`patterns = [".env", ".env.local"]`);
    lines.push(``);
  }

  // [hooks]
  lines.push(`[hooks]`);
  lines.push(`# pre_install = ["echo 'Starting setup...'"]`);
  if (hasNode) {
    lines.push(`# post_install = ["bun run codegen"]`);
  } else if (hasPython) {
    lines.push(`# post_install = ["python manage.py migrate --check"]`);
  }
  lines.push(`# post_setup = ["echo 'Worktree ready!'"]`);
  lines.push(``);

  // [worktree]
  lines.push(`[worktree]`);
  lines.push(`base_dir = "../worktrees/${repoName}"`);
  lines.push(`name_pattern = "{repo}-{short_branch}"`);
  lines.push(``);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Simple interactive prompt (readline without framework)
// ---------------------------------------------------------------------------

async function prompt(question: string): Promise<string> {
  process.stdout.write(question);
  const buffer: number[] = [];
  return new Promise((resolve) => {
    process.stdin.resume();
    process.stdin.setEncoding("utf8");
    const onData = (chunk: string) => {
      const newlineIdx = chunk.indexOf("\n");
      if (newlineIdx !== -1) {
        const line = chunk.slice(0, newlineIdx);
        process.stdin.pause();
        process.stdin.removeListener("data", onData);
        resolve(line.trim());
      }
    };
    process.stdin.on("data", onData);
  });
}

// ---------------------------------------------------------------------------
// Main command
// ---------------------------------------------------------------------------

export default async function initCommand(
  _args: string[],
  flags: ParsedFlags,
): Promise<number> {
  if (flags.help) {
    logger.info(HELP);
    return 0;
  }

  const useDefaults = flags.defaults === true;
  const cwd = process.cwd();

  // --- Resolve repo root -------------------------------------------------
  const repoRoot = await getRepoRoot(cwd);
  if (!repoRoot) {
    logger.error("Not inside a git repository.");
    return 1;
  }

  const rcPath = path.join(repoRoot, ".worktreerc");
  const repoName = path.basename(repoRoot);

  // --- Check if .worktreerc already exists ------------------------------
  try {
    await fs.access(rcPath);
    if (!useDefaults) {
      logger.warn(`.worktreerc already exists at ${rcPath}`);
      const answer = await prompt("Overwrite? [y/N] ");
      if (answer.toLowerCase() !== "y" && answer.toLowerCase() !== "yes") {
        logger.info("Aborted.");
        return 0;
      }
    } else {
      logger.warn(`.worktreerc already exists — overwriting (--defaults).`);
    }
  } catch {
    // file doesn't exist — proceed
  }

  // --- Detect ecosystems ------------------------------------------------
  logger.info("Scanning project...");
  const ecosystems = await detectProjectTypes(repoRoot);
  if (ecosystems.length > 0) {
    logger.result("Detected", ecosystems.map((e) => `${e.type}(${e.pm})`));
  } else {
    logger.info("  No ecosystems detected.");
  }

  // --- Scan for .env files ---------------------------------------------
  const envFiles = await findEnvFiles(repoRoot);
  if (envFiles.length > 0) {
    logger.result(".env files", envFiles);
  } else {
    logger.info("  No .env files found.");
  }

  // --- Build content ---------------------------------------------------
  const content = buildWorktreerc(ecosystems, envFiles, repoName);

  // --- Preview and confirm --------------------------------------------
  if (!useDefaults) {
    logger.blank();
    logger.info(`Will write to: ${rcPath}`);
    logger.info("Content preview:");
    logger.info("---");
    for (const line of content.split("\n")) {
      logger.info(line);
    }
    logger.info("---");
    logger.blank();

    const answer = await prompt("Write this .worktreerc? [Y/n] ");
    if (answer.toLowerCase() === "n" || answer.toLowerCase() === "no") {
      logger.info("Aborted.");
      return 0;
    }
  }

  // --- Write the file --------------------------------------------------
  await Bun.write(rcPath, content);
  logger.success(`Created ${rcPath}`);
  logger.info("");
  logger.info("Next steps:");
  logger.info("  1. Review and customize .worktreerc");
  logger.info("  2. Commit it:  git add .worktreerc && git commit -m 'chore: add worktreerc'");
  logger.info("  3. Add .wt-status.json to .gitignore");

  return 0;
}
